sim: Create parent directories if necessary

diff --git a/bin/sim b/bin/sim
--- a/bin/sim
+++ b/bin/sim
@@ -44,7 +44,12 @@ function sim_create()
 
     echo "Creating simulation $simdir"
 
-    mkdir $simdir
+    if [ -r $simdir ]; then
+        echo "$0: Cannot create simulation because simulation directory $simdir already exists" >&2
+        exit 1
+    fi
+
+    mkdir -p $simdir
     mkdir $simdir/code
     mkdir $simdir/meta
 
